package gui.createpanels;

import java.awt.BorderLayout;
import java.awt.Dimension;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * This input panel allows the user to enter information for a specific field
 * that any instance of this class could be assigned.
 * 
 * @author Eric
 * @since 6/5/19
 */
public class FieldInputPanel extends JPanel {

	private static final long serialVersionUID = 1L;

	private final String myFieldName;

	private final String myFieldDescription;

	private final String myFieldValueType;

	private final JTextField myInputField;

	/**
	 * Creates a field input panel which allows users to enter information into the
	 * field generated by the item-type they've selected from the schema.
	 * 
	 * @author Eric
	 * @since 6/5/19
	 */
	public FieldInputPanel(final String theFieldName, final String theFieldDescription,
			final String theFieldValueType) {
		this.myFieldDescription = theFieldDescription;
		this.myFieldValueType = theFieldValueType;
		this.myFieldName = theFieldName;
		this.setLayout(new BorderLayout());
		this.setBorder(BorderFactory.createBevelBorder(3));
		this.setPreferredSize(new Dimension(150, 60));
		this.setMaximumSize(new Dimension(160, 60));
		final JLabel fieldNameLabel = new JLabel(theFieldName);
		this.add(fieldNameLabel, BorderLayout.NORTH);
		myInputField = new JTextField();
		myInputField.setMinimumSize(new Dimension(100, 50));
		myInputField.setEditable(true); // this is where they put the value.
		this.add(myInputField, BorderLayout.CENTER);
	}

	/**
	 * Returns the field name.
	 * 
	 * @return the name of this field.
	 * @author Eric
	 * @since 6/5/19
	 */
	public String getFieldName() {
		// Grab the field name showed on the label.
		return myFieldName;
	}

	/**
	 * Returns the Value of this field.
	 * 
	 * @return the Value of this field.
	 * @author Eric
	 * @since 6/5/19
	 */
	public String getValue() {
		// Grab the value stored in the input field.
		return myInputField.getText();
	}

	/**
	 * Returns the description of this field.
	 * 
	 * @return the description of this field.
	 * @author Eric
	 * @since 6/5/19
	 */
	public String getDescription() {
		return myFieldDescription;
	}

	/**
	 * Returns the field value-type.
	 * 
	 * @return the value-type of this field.
	 * @author Eric
	 * @since 6/5/19
	 */
	public String getValueType() {
		return myFieldValueType;
	}
}
